global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'wolf-engine'
    static_configs:
      - targets: ['wolf-engine:9101']

  - job_name: 'wolf-allocation'
    static_configs:
      - targets: ['wolf-allocation:9102']

  - job_name: 'wolf-ingest'
    static_configs:
      - targets: ['wolf-ingest:9103']

  - job_name: 'wolf-dashboard'
    static_configs:
      - targets: ['wolf-dashboard:9104']

