import {VIEWS,escapeHTML as e,text,number,money,timestamp,precision,precisionDelta,freshness,payload,list,filterPairs,safeJSON} from './model.mjs';
const paths={grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',radar:'M12 3a9 9 0 1 0 9 9 M12 7a5 5 0 1 0 5 5 M12 12l8-8 M12 12h.01',trace:'M4 5h4v4H4z M16 15h4v4h-4z M8 7h8v10 M4 17h7',ring:'M12 3a9 9 0 1 0 9 9 M12 3v9h9 M16 3.9a9 9 0 0 1 4.1 4.1',activity:'M2 12h4l3-8 5 16 3-8h5',signal:'M3 18v3 M9 13v8 M15 8v13 M21 3v18',audit:'M5 3h14v18H5z M9 8h6 M9 12h6 M9 16h3',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z',code:'m8 6-6 6 6 6 M16 6l6 6-6 6 M14 3l-4 18',refresh:'M20 7V3l-3 3a8 8 0 1 0 2 11 M20 3h-5',logout:'M9 3H4v18h5 M9 12h12 M17 8l4 4-4 4',search:'M20 20l-5-5 M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0',lock:'M5 10h14v11H5z M8 10V7a4 4 0 0 1 8 0v3 M12 14v3',info:'M12 16v-4 M12 8h.01 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',menu:'M3 6h18 M3 12h18 M3 18h18',close:'m5 5 14 14 M5 19 19 5',clock:'M12 7v5l3 2 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0'};
export const icon=k=>`<svg aria-hidden="true" viewBox="0 0 24 24"><path d="${paths[k]||paths.info}"/></svg>`;
export const badge=(label,kind='')=>`<span class="badge ${kind}">${e(label)}</span>`;
function status(v){const s=text(v);return badge(s,/^(FRESH|HEALTHY|VALID)$/.test(s)?'green':/STALE|WAIT|HOLD|ABSENT/.test(s)?'amber':/ERROR|FAIL|BLOCKED/.test(s)?'red':'');}
const link=(path,label,cls='')=>`<a class="${cls}" href="#/${e(path)}" data-route="${e(path)}">${label}</a>`;
const metric=(label,value)=>`<div class="metric"><span>${e(label)}</span><strong>${e(text(value))}</strong></div>`;
const observationNames={overview:'System overview',feed:'Feed status',pairs:'Pair projection',traces:'Lifecycle projection',risk:'Account snapshot',execution:'Execution snapshot',audit:'Audit projection',mcp:'MCP evidence'};
function sourceFoot(key,o){return `<div class="section-foot"><span>${e(o?.source||'Sumber belum terhubung')} · ${e(timestamp(o?.asOf))} · <span data-freshness="${key}">${freshness(o)}</span></span><button class="source-button" data-source="${e(key)}">Detail bukti</button></div>`;}
function panel(title,body,meta='',cls=''){return `<article class="panel ${cls}"><div class="panel-head"><h2>${title}</h2>${meta}</div>${body}</article>`;}
function unavailable(o,label,ico='signal'){
  const failed=o?.state==='error'||o?.state==='schema_error';
  const heading=failed?'Data belum dapat ditampilkan':o?.state==='ready'?'Tidak ada data pada cakupan ini':'Data belum tersedia';
  const reason=failed?(o.state==='schema_error'?'Bentuk respons belum sesuai kontrak tampilan.':'Permintaan gagal. Periksa sumber atau muat ulang melalui sesi viewer.'):`${label} akan muncul setelah snapshot sumber tersedia.`;
  return `<div class="empty"><div class="empty-icon">${icon(ico)}</div><h3>${heading}</h3><p>${e(reason)}</p>${link('data-sistem','Lihat Data Sistem →')}<small>${failed?'SOURCE_UNAVAILABLE':o?.state==='ready'?'EMPTY_IN_SCOPE':'NOT_MEASURED'}</small></div>`;
}
function kpi(label,value,note,ico='activity',color=''){return `<article class="panel kpi"><div class="kpi-label"><span>${e(label)}</span><span class="kpi-icon">${icon(ico)}</span></div><div class="kpi-value ${color}">${e(value)}</div><div class="kpi-note">${e(note)}</div></article>`;}
function pairRows(items){return items.map(p=>`<tr><td>${link(`5s-cr?symbol=${encodeURIComponent(p.symbol||'')}&lifecycle=${encodeURIComponent(p.lifecycleId||'')}`,e(text(p.symbol)),'pair-link')}</td><td>${e(text(p.pressure))}</td><td>${status(p.lifecycleState)}</td><td>${e(text(p.strategyStage))}</td><td>${e(text(p.admission))}</td><td>${status(p.quality)}</td></tr>`).join('');}
function pairTable(items){return `<div class="table-wrap"><table><thead><tr><th>Pasangan</th><th>Pressure</th><th>Lifecycle</th><th>Strategy stage</th><th>Admission</th><th>Kualitas</th></tr></thead><tbody>${pairRows(items)}</tbody></table></div>`;}
function stages(trace){
  const names=['Admission','Lifecycle','Context','Proof','Geometry'];
  return `<div class="pipeline">${names.map((n,i)=>{const found=trace?.stages?.find(s=>s.stage===`S${i+1}`);const state=found?.state;return `<div class="stage ${state==='COMPLETE'?'done':state==='WAIT'?'wait':''}"><div class="step"><span>S${i+1}</span><span>${state==='COMPLETE'?'✓':'·'}</span></div><h3>${n}</h3><div class="stage-value">${e(state||'Belum terukur')}</div></div>`;}).join('')}</div>`;
}
function overview(m){
  const d=payload(m.overview)||{};const pairs=list(m.pairs);const feed=payload(m.feed)||{};
  const kpis=`<div class="grid kpis">${kpi('Status sistem',text(d.systemState),d.systemState?'Status dari proyeksi sistem':'Menunggu snapshot overview','activity')}${kpi('Kualitas feed',text(feed.qualityState),'Koneksi dan kualitas dinilai terpisah','signal')}${kpi('Lifecycle aktif',number(d.activeLifecycles),'Jumlah hanya dari sumber terikat','trace')}${kpi('Eksekusi sistem',text(d.executionState),'Berbeda dari hak akses dashboard','lock')}</div>`;
  const queue=Array.isArray(d.incidents)&&d.incidents.length?`<div class="panel-body">${d.incidents.map(i=>`<div class="notice"><div class="statusline">${status(i.severity)}</div><strong>${e(i.title)}</strong><p>${e(i.reason||'')}</p><button class="source-button" data-source="overview">${e(i.evidenceRef||'Detail sumber')}</button></div>`).join('')}</div>`:unavailable(m.overview,'Insiden teramati','info');
  const identity=`<div class="panel-body">${metric('Environment',m.identity.environment)}${metric('Mode sistem',m.identity.mode)}${metric('Versi strategi',m.identity.strategyVersion)}${metric('Deployment frontend',m.identity.deploymentId)}${metric('Source SHA',m.identity.sha)}</div>`;
  return kpis+`<div class="grid columns">${panel('Pair radar',pairs.length?pairTable(pairs.slice(0,5)):unavailable(m.pairs,'Pasangan dan lifecycle','radar'),link('pair-radar','Lihat semua →','meta'))}${panel('Perlu perhatian',queue,badge('OBSERVASI'))}</div>`+
   `<div class="grid columns">${panel('Alur 5S-CR',stages(null)+`<div class="section-foot"><span>Urutan proses · pilih lifecycle untuk melihat bukti tiap tahap</span>${link('5s-cr','Telusuri →')}</div>`,badge('PETA PROSES'))}${panel('Identitas runtime',identity,badge(m.identity.environment?'SUMBER':'NOT_MEASURED'))}</div>`+
   panel('Sumber data operasional',`<div class="panel-body"><div class="grid equal" style="margin:0">${['overview','feed'].map(k=>`<div>${metric(observationNames[k],m[k].state==='ready'?'Respons tersedia':'Belum tersedia')}${metric('Waktu sumber',timestamp(m[k].asOf))}${metric('Freshness',freshness(m[k]))}</div>`).join('')}</div></div><div class="section-foot"><span>Tiga panel frontend asli tetap tersedia di halaman khusus.</span>${link('data-sistem','Buka Data Sistem →')}</div>`,badge('READ ONLY'));
}
function radar(m,ui){const items=filterPairs(list(m.pairs),ui.query,ui.filter);if(ui.sort==='symbol')items.sort((a,b)=>String(a.symbol).localeCompare(String(b.symbol)));else if(ui.sort==='stage')items.sort((a,b)=>String(a.strategyStage).localeCompare(String(b.strategyStage)));
  const max=Math.max(1,Math.ceil(items.length/20));const page=Math.min(ui.tablePage,max);const shown=items.slice((page-1)*20,page*20);
  return `<div class="toolbar"><div class="tabs">${[['all','Semua'],['wait','WAIT'],['no-trade','NO_TRADE'],['stale','Stale']].map(([id,name])=>`<button class="tab" data-filter="${id}" aria-pressed="${ui.filter===id}">${name}</button>`).join('')}</div><div class="actions"><div class="input-wrap">${icon('search')}<input data-search aria-label="Cari pasangan" placeholder="Cari pasangan…" value="${e(ui.query)}"></div><select data-sort aria-label="Urutkan pasangan"><option value="symbol" ${ui.sort==='symbol'?'selected':''}>Urutan pasangan</option><option value="stage" ${ui.sort==='stage'?'selected':''}>Strategy stage</option></select></div></div>`+
   panel('Pasangan dalam snapshot',shown.length?pairTable(shown):unavailable(m.pairs,items.length===0&&list(m.pairs).length?'Hasil filter':'Pair radar','radar'),badge(`${items.length} TERLIHAT`))+
   `<div class="section-foot"><span>${list(m.pairs).length?'Cakupan daftar sesuai snapshot; bukan seluruh sistem.':'Jumlah total sistem: belum terukur.'}</span><div class="actions"><button class="button quiet" data-page-step="-1" ${page<=1?'disabled':''}>Sebelumnya</button><span>${page} / ${max}</span><button class="button quiet" data-page-step="1" ${page>=max?'disabled':''}>Berikutnya</button></div></div>`+sourceFoot('pairs',m.pairs);
}
function trace(m,route){const symbol=route.params.get('symbol');const lifecycle=route.params.get('lifecycle');const all=list(m.traces);const match=all.filter(t=>t.symbol===symbol&&t.lifecycleId===lifecycle);const revision=route.params.get('revision');const chosen=revision?match.find(t=>String(t.revision)===revision):[...match].sort((a,b)=>Number(b.revision)-Number(a.revision))[0];
  const select=match.length?`<select data-revision aria-label="Pilih revisi lifecycle">${match.map(t=>`<option value="${e(t.revision)}" ${t.revision===chosen?.revision?'selected':''}>Revisi ${e(t.revision)}</option>`).join('')}</select>`:'';
  const events=chosen?.events;const timeline=events?.length?`<div class="panel-body">${events.map(ev=>`<div class="timeline-item"><time>${e(timestamp(ev.asOf))}</time><div><b>${e(ev.title)}</b><p>${e(ev.reason||'')}</p><span class="meta">${e(ev.evidenceRef||'Referensi belum tersedia')}</span></div></div>`).join('')}</div>`:unavailable(m.traces,'Timeline lifecycle ini','trace');
  return `<div class="toolbar"><div><h2>${e(symbol||'Pilih pasangan dari Pair Radar')}</h2><p class="meta">Lifecycle: ${e(lifecycle||'belum dipilih')} · Revisi: ${e(text(chosen?.revision))}</p></div>${select}</div>`+
   panel('Jejak 5S-CR',stages(chosen),chosen?status(chosen.lifecycleState):badge('NOT_MEASURED'))+
   `<div class="grid columns" style="margin-top:20px">${panel('Timeline evidence',timeline)}${panel('Konteks & keputusan',`<div class="panel-body">${metric('Source stage',chosen?.sourceStage)}${metric('Strategy stage',chosen?.strategyStage)}${metric('Admission',chosen?.admission)}${metric('Reason code',chosen?.reasonCode)}${metric('Context epoch',chosen?.contextEpoch)}${metric('Next trigger',chosen?.nextTrigger)}</div><div class="section-foot">Candidate tidak berarti risk authorized atau executed.</div>`)}</div>`+sourceFoot('traces',m.traces);
}
function risk(m){const d=payload(m.risk)||{};const pct=typeof d.utilizationPct==='number'&&d.utilizationPct>=0&&d.utilizationPct<=100?d.utilizationPct:null;
  return `<div class="grid kpis">${kpi('Balance',money(d.balance,d.currency),'Snapshot akun teredaksi','ring')}${kpi('Equity',money(d.equity,d.currency),'Tidak dihitung ulang frontend','activity')}${kpi('Free margin',money(d.freeMargin,d.currency),'Mata uang mengikuti sumber','ring')}${kpi('Risiko terbuka',d.openRiskPct==null?'—':number(d.openRiskPct)+'%','Nilai dari pemilik risk','lock')}</div>`+
   `<div class="grid columns">${panel('Snapshot akun',`<div class="panel-body">${metric('Account alias',d.accountAlias)}${metric('Currency',d.currency)}${metric('Kebijakan risk',d.policyId)}${metric('Reconciliation',d.reconciliation)}${metric('Waktu sumber',timestamp(m.risk.asOf))}</div>`)}${panel('Pemakaian batas risiko',`<div class="panel-body"><div class="ring" ${pct==null?'':`style="background:conic-gradient(var(--amber) ${pct}%,#203a43 0)"`}><div class="ring-inner"><b>${pct==null?'—':number(pct)+'%'}</b><small>${pct==null?'Belum terukur':'Dari sumber risk'}</small></div></div><p class="meta" style="text-align:center">Rasio hanya ditampilkan bila tersedia dari snapshot risk.</p></div>`)}</div>`+sourceFoot('risk',m.risk);
}
function execution(m){const d=payload(m.execution)||{};const rows=list(m.execution);
  return `<div class="banner"><div class="left">${icon('lock')}<span>Observasi eksekusi <span class="meta">· tidak ada aksi order, retry, atau cancel</span></span></div>${badge('READ ONLY','cyan')}</div><div class="grid kpis">${kpi('Flag execution',text(d.enabledState),'FALSE dan ABSENT tetap dibedakan','lock')}${kpi('Command dalam scope',number(d.commandCount),'Jumlah eksplisit dari proyeksi','code')}${kpi('Heartbeat executor',text(d.heartbeatState),'Status pada waktu observasi','activity')}${kpi('Reconciliation',text(d.reconciliation),'Bukan otorisasi trading','audit')}</div>`+
   panel('Command & laporan',rows.length?`<div class="table-wrap"><table><thead><tr><th>Command</th><th>Pair</th><th>Status</th><th>Lease</th><th>Broker report</th><th>Teramati</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${e(r.commandId)}</td><td>${e(text(r.symbol))}</td><td>${status(r.state)}</td><td>${e(text(r.leaseState))}</td><td>${e(text(r.reportState))}</td><td class="meta">${e(timestamp(r.asOf))}</td></tr>`).join('')}</tbody></table></div>`:unavailable(m.execution,'Status command dan laporan','activity'),badge(freshness(m.execution)))+sourceFoot('execution',m.execution);
}
function quality(m){const d=payload(m.feed)||{};const rows=list(m.feed);
  return `<div class="grid kpis">${kpi('Status koneksi',text(d.connectionState),'Sesuai respons feed-status','signal')}${kpi('Kualitas data',text(d.qualityState),'Tidak disimpulkan dari HTTP 200','activity')}${kpi('Gap candle',number(d.candleGapCount),'Kosong tidak dianggap nol','trace')}${kpi('Freshness',freshness(m.feed),'Timestamp sumber + policy','clock')}</div>`+
   panel('Feed & quote quality',rows.length?`<div class="table-wrap"><table><thead><tr><th>Symbol / stream</th><th>Provider</th><th>Transport</th><th>State</th><th>Quote quality</th><th>Last valid event</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${e(text(r.symbol))}</td><td>${e(text(r.provider))}</td><td>${e(text(r.transport))}</td><td>${status(r.state)}</td><td>${status(r.quality)}</td><td class="meta">${e(timestamp(r.lastEventAt))}</td></tr>`).join('')}</tbody></table></div>`:unavailable(m.feed,'Feed dan kualitas quote','signal'),link('data-sistem?panel=feedStatus','Payload feed-status →','meta'))+sourceFoot('feed',m.feed);
}
function audit(m){const d=payload(m.audit)||{};const rows=list(m.audit,'reports');const latest=rows[0];
  return `<div class="grid kpis">${kpi('Presisi periode',precision(latest),'Dari laporan; denominator terminal > 0','audit')}${kpi('Outcome terminal',number(latest?.terminalDenominator),'0 valid; null berarti belum terukur','trace')}${kpi('Perubahan presisi',precisionDelta(d),'Harus berasal dari cohort sebanding','activity')}${kpi('Execution readiness',text(d.executionReadiness),'Hasil audit, bukan keputusan UI','lock')}</div>`+
   panel('Audit per periode',rows.length?`<div class="table-wrap"><table><thead><tr><th>Periode UTC</th><th>Outcome</th><th>Denominator terminal</th><th>Presisi</th><th>Manifest / alasan</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${e(text(r.periodStart))}<br><span class="meta">s.d. ${e(text(r.periodEnd))}</span></td><td>${e(number(r.outcomeCount))}</td><td>${e(number(r.terminalDenominator))}</td><td>${e(precision(r))}</td><td class="meta">${e(r.manifestId||'Manifest belum tersedia')}<br>${e(r.reason||'')}</td></tr>`).join('')}</tbody></table></div>`:unavailable(m.audit,'Hasil audit dan replay terikat manifest','audit'),badge('SNAPSHOT'))+
   `<div class="notice" style="margin-top:20px"><strong>Denominator yang tepat</strong>WAIT, NO_TRADE, candidate, filled, dan closed tetap terpisah. Tidak ada garis performa sebelum seri hasil terverifikasi tersedia.</div>`+sourceFoot('audit',m.audit);
}
function mcp(){return `<div class="grid columns">${panel('MCP Evidence Copilot',`<div class="empty" style="min-height:330px"><div class="empty-icon">${icon('spark')}</div><h3>Belum terhubung</h3><p>Penjelasan akan tersedia setelah layanan query read-only dan referensi bukti terhubung.</p><small>Tidak ada jawaban atau evidence simulasi.</small></div><div class="panel-body"><div class="copilot-form"><input disabled aria-label="Pertanyaan MCP belum tersedia" placeholder="Tanyakan alasan status sebuah lifecycle…"><button class="button" disabled>Kirim</button></div></div>`,badge('NOT_CONNECTED','amber'))}${panel('Bukti yang menyertai jawaban',`<div class="panel-body"><div class="notice"><strong>Reason code</strong>Penjelasan ditautkan ke keputusan dan lifecycle yang tepat.</div><div class="notice"><strong>Referensi sumber</strong>Trace ID, waktu observasi, dan revisi tersedia untuk diperiksa.</div><div class="notice"><strong>Hak akses viewer</strong>Hanya membaca proyeksi yang telah diizinkan.</div></div>`)}</div>`;}
function evidence(m,route){const titles={overview:'System overview',feedStatus:'Feed status',aggregatedStatus:'Aggregated status'};
  const fallback=Object.entries(titles).map(([k,title])=>{const o=m.evidence[k];const has=o.state==='ready';return `<article class="panel evidence-card" id="panel-${k}"><details ${route.params.get('panel')===k||k==='overview'?'open':''}><summary class="panel-head"><h2>${title}</h2>${badge(has?'RESPONS TERSEDIA':'BELUM TERHUBUNG',has?'cyan':'')}</summary><div class="evidence-grid"><div class="mini">Source<strong>${e(o.source||'Belum tersedia')}</strong></div><div class="mini">Request ID<strong>${e(o.requestId||'Belum tersedia')}</strong></div><div class="mini">Waktu sumber<strong>${e(timestamp(o.asOf))}</strong></div></div>${has?`<pre class="code">${e(safeJSON(o.data))}</pre><div class="section-foot">Payload sumber · field kredensial disamarkan bila ada.</div>`:unavailable(o,title,'code')}</details></article>`;}).join('');
  return `<div class="banner"><div class="left">${icon('code')}<div><strong>Tiga panel frontend asli</strong><div class="meta">System overview · Feed status · Aggregated status</div></div></div>${badge('DATA SISTEM','cyan')}</div>${m.connection==='connected'?`<slot name="system-evidence">${fallback}</slot>`:fallback}`;
}
export function renderPage(m,route,ui){const renderers={'command-center':()=>overview(m),'pair-radar':()=>radar(m,ui),'5s-cr':()=>trace(m,route),'risk-account':()=>risk(m),'execution':()=>execution(m),'data-quality':()=>quality(m),'audit-replay':()=>audit(m),'mcp':()=>mcp(m),'data-sistem':()=>evidence(m,route)};return renderers[route.page]();}
export function renderShell(m,route,ui,options={}) {
  const title=VIEWS.find(v=>v[0]===route.page)[1];
  const descriptions={'command-center':'Kondisi sistem, kualitas sumber, dan lifecycle dalam satu pandangan.','pair-radar':'Temukan pasangan yang membutuhkan perhatian berdasarkan snapshot sumber.','5s-cr':'Ikuti keputusan per pasangan, lifecycle, dan revisi.','risk-account':'Baca kondisi akun dan risiko dari pemilik datanya.','execution':'Pantau command, heartbeat, dan reconciliation.','data-quality':'Periksa kontinuitas feed dan kualitas observasi pasar.','audit-replay':'Baca hasil dalam konteks periode, cohort, dan manifest.','mcp':'Telusuri alasan keputusan dengan referensi bukti.','data-sistem':'Panel teknis frontend yang sudah ada, dikumpulkan di halaman tersendiri.'};
  const nav=VIEWS.map(([id,label,,ico],i)=>`${i===0?'<div class="nav-label">OPERASIONAL</div>':i===6?'<div class="nav-label">BUKTI & DATA</div>':''}<a href="#/${id}" data-route="${id}" class="nav-link" ${route.page===id?'aria-current="page"':''}>${icon(ico)}<span>${label}</span><span class="chevron">›</span></a>`).join('');
  const connected=m.connection==='connected';
  const banner=connected?'':`<div class="banner warning" role="status"><div class="left">${icon('info')}<div><strong>${m.connection==='session_expired'?'Sesi viewer berakhir':m.connection==='forbidden'?'Akses viewer tidak tersedia':'Pratinjau desain · koneksi sistem belum tersedia'}</strong><div class="meta">${['forbidden','session_expired'].includes(m.connection)?'Data sesi sebelumnya telah dibersihkan. Gunakan login frontend yang sudah ada.':'Tidak ada angka simulasi. Nilai muncul setelah data asli dipetakan.'}</div></div></div>${badge(connected?'':'NOT_CONNECTED','amber')}</div>`;
  return `<div class="shell"><button class="overlay ${ui.menu?'visible':''}" data-action="close-menu" aria-label="Tutup navigasi"></button><aside class="sidebar ${ui.menu?'open':''}" ${ui.menu?'role="dialog" aria-label="Menu navigasi"':''}><div class="brand"><div class="brand-mark">W15</div><div><b>WOLF15</b><small>Operations Console</small></div></div><nav aria-label="Navigasi dashboard">${nav}</nav><div class="sidebar-foot">${badge('OBSERVATIONAL ONLY','cyan')}<p>Dashboard tidak memiliki<br>otoritas eksekusi.</p><div class="viewer"><div class="avatar">V</div><div><strong>${connected?'Viewer':'Preview'}</strong><br>Read only</div><button class="icon-button" data-action="logout" aria-label="Log out" ${options.canLogout?'':'disabled'}>${icon('logout')}</button></div></div></aside><div class="body"><header class="topbar"><div class="breadcrumbs"><button class="icon-button mobile-toggle" aria-label="Buka navigasi" aria-expanded="${ui.menu}" data-action="menu">${icon('menu')}</button><span>WOLF-15 LAYER</span><span>/</span><strong>${e(title)}</strong></div><div class="actions">${badge(connected?'VIEWER · READ ONLY':'DESIGN PREVIEW',connected?'cyan':'')}<button class="button primary" data-action="refresh" ${options.canRefresh?'':'disabled'}>${icon('refresh')}<span>Refresh</span></button></div></header><main class="content"><div class="heading"><div><div class="overline">${e(m.identity.environment||'WOLF15 · OBSERVASI')}</div><h1 tabindex="-1">${e(title)}</h1><p class="subtitle">${descriptions[route.page]}</p></div><div class="meta">Diterima frontend<br><strong>${e(timestamp(m.receivedAt))}</strong></div></div>${banner}<div data-view>${renderPage(m,route,ui)}</div><footer class="version-note"><span>OBSERVATIONAL_ONLY · NO EXECUTION AUTHORITY</span><span>Waktu sumber dan waktu refresh ditampilkan terpisah.</span></footer></main></div></div>`;
}
export function renderSource(m,key){const o=m[key];if(!o)return '';return `<div class="sheet" data-action="dismiss-sheet"><section class="sheet-content" role="dialog" aria-modal="true" aria-labelledby="evidence-title"><div class="sheet-head"><h2 id="evidence-title">Detail bukti</h2><button class="icon-button" data-action="close-sheet" aria-label="Tutup detail">${icon('close')}</button></div><div class="overline">${e(observationNames[key])}</div>${metric('State',o.state)}${metric('Source',o.source)}${metric('As of',timestamp(o.asOf))}${metric('Diterima frontend',timestamp(m.receivedAt))}${metric('Request ID',o.requestId)}${metric('Freshness',freshness(o))}${metric('Freshness policy',o.freshness?.policyId)}<p class="meta" style="margin-top:20px">Request ID tidak otomatis merupakan trace ID upstream. Perbedaan SHA antarlayanan memerlukan kebijakan compatibility untuk dinilai.</p>${link('data-sistem','Buka tiga panel asli →','button quiet')}</section></div>`;}
